export const E6_CONFIG_STATUS = Object.freeze({
  DISABLED: 0,
  ENABLED: 1,
});

export const E6_MAPPING_STATUS = Object.freeze({
  DISABLED: 0,
  ENABLED: 1,
});

export const E6_IMPORT_STATUS = Object.freeze({
  IMPORT_PENDING: 0,
  IMPORT_MAPPING_REQUIRED: 1,
  IMPORT_ERROR: 2,
  IMPORT_CONVERTED: 3,
  IMPORT_REJECTED: 4,
  IMPORT_CANCELLED: 5,
  IMPORT_CONFLICT: 6,
  IMPORT_PROCESSING: 7,
});

export const E6_IMPORT_STATUS_VALUES = Object.freeze(
  Object.values(E6_IMPORT_STATUS),
);

export const E6_ERROR_CODE = Object.freeze({
  DOCTOR_MAPPING_REQUIRED: "DOCTOR_MAPPING_REQUIRED",
  DATA_CHANGED_AFTER_CONVERSION: "DATA_CHANGED_AFTER_CONVERSION",
  CONVERSION_FAILED: "CONVERSION_FAILED",
});

export const E6_SOURCE_CODE = "E6";
