export const PROCESSING_WORKFLOW_VERSION = 2;

export const PROCESSING_STAGE = Object.freeze({
  DISPENSING: "DISPENSING",
  DISPENSING_DONE: "DISPENSING_DONE",
  SOAKING: "SOAKING",
  DECOCTING: "DECOCTING",
  PACKAGING: "PACKAGING",
  PACKAGING_DONE: "PACKAGING_DONE",
  COMPLETED: "COMPLETED",
});

export const EQUIPMENT_TYPE = Object.freeze({
  SOAK_BUCKET: "SOAK_BUCKET",
  DECOCTION_POT: "DECOCTION_POT",
  PACKAGING_MACHINE: "PACKAGING_MACHINE",
});

export const EQUIPMENT_TYPE_NAMES = Object.freeze({
  [EQUIPMENT_TYPE.SOAK_BUCKET]: "浸泡桶",
  [EQUIPMENT_TYPE.DECOCTION_POT]: "煎药机",
  [EQUIPMENT_TYPE.PACKAGING_MACHINE]: "包装机",
});

export const EQUIPMENT_STATUS = Object.freeze({
  DISABLED: 0,
  ENABLED: 1,
  MAINTENANCE: 2,
});

export const PROCESSING_PHOTO_KIND = Object.freeze({
  DISPENSING_COMPLETED: "DISPENSING_COMPLETED",
});

export const PROCESSING_PHOTO_MAX_SIZE = 5 * 1024 * 1024;
export const PROCESSING_PHOTO_MAX_COUNT = 3;
