export const PRODUCT_DIFF_OPERATION = Object.freeze({
  PRE_RECEIPT: "PRE_RECEIPT",
  PRE_SHIPMENT: "PRE_SHIPMENT",
  WRITE_OFF_RECEIPT: "WRITE_OFF_RECEIPT",
  WRITE_OFF_SHIPMENT: "WRITE_OFF_SHIPMENT",
  REVERSAL: "REVERSAL",
  IMPORT_OPENING: "IMPORT_OPENING",
  IMPORT_ADJUSTMENT: "IMPORT_ADJUSTMENT",
});

export const REGISTER_OPERATION_VALUES = Object.freeze([
  PRODUCT_DIFF_OPERATION.PRE_RECEIPT,
  PRODUCT_DIFF_OPERATION.PRE_SHIPMENT,
]);

export const PRODUCT_DIFF_OPERATION_VALUES = Object.freeze(
  Object.values(PRODUCT_DIFF_OPERATION),
);

export function registerQuantitySign(operationType) {
  if (operationType === PRODUCT_DIFF_OPERATION.PRE_RECEIPT) return 1;
  if (operationType === PRODUCT_DIFF_OPERATION.PRE_SHIPMENT) return -1;
  return 0;
}
